<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.6.2</Version>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
    <CsWinRTComponent>true</CsWinRTComponent>
    <Platforms>x86;x64;ARM64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateProgramFile>false</GenerateProgramFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='x86'">
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='ARM64'">
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
    <ProjectReference Include="..\GDG.VirtualPrinter.Core\GDG.VirtualPrinter.Core.csproj" />
  </ItemGroup>
</Project>
