<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.6.2</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x86;x64;ARM64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateProgramFile>false</GenerateProgramFile>
    <AssemblyName>GDG.VirtualPrinter.Host</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='x86'">
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='ARM64'">
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GDG.VirtualPrinter.Core\GDG.VirtualPrinter.Core.csproj" />
    <ProjectReference Include="..\GDG.VirtualPrinter.VirtualPrinter\GDG.VirtualPrinter.VirtualPrinter.csproj" />
    <ProjectReference Include="..\GDG.VirtualPrinter.Launcher\GDG.VirtualPrinter.Launcher.csproj" />
  </ItemGroup>
</Project>
